### ISSUE TITLE
Flatpacker 1001 is fucked

### ISSUE THREAD

**Issue by therealDLondon** [DeltaV-Station/Delta-v#1536]
## Description
Flatpacker spits out a base flatpack instead of the requested flatpack, and eats mats

**Reproduction**
Get flatpacker. Fill with mats. Give board. Print. Weep.

**Additional context**
Happened after upstream merge

**Comment by deltanedas** [comment]
its from throwing an exception midway, provide loggie

**Comment by redmushie** [comment]
Fixed upstream by https://github.com/space-wizards/space-station-14/pull/28736

**Comment by OrangeMoronage9622** [comment]
Still happens right now. Currently crying at my SMES maxxing plans being ruined.
