### ISSUE TITLE
Station AI unable to hear when projecting to HoloPad

### ISSUE THREAD

**Issue by DisposableCrewmember42** [DeltaV-Station/Delta-v#2602]
## Description
Station AI can't hear local chat when projecting to a holopad.

**Reproduction**
1. Play Station AI
2. Project to pad or receive call
3. Be able to speak in Local, but not hear in Local.

**Comment by DisposableCrewmember42** [comment]
This was happening in Round 18403 on Edge.

**Comment by deltanedas** [comment]
fixed in upstream merge just wait

**Comment by DisposableCrewmember42** [comment]
Still happening, current round on Peri (upstream merge is shown in changelog). It seems like the location of the hearing entity isn't updated correctly:

https://github.com/user-attachments/assets/812dfe08-6142-4780-86ee-5784ac903d26

**Comment by DisposableCrewmember42** [comment]
@deltanedas

**Comment by DisposableCrewmember42** [comment]
Uh, I think this is either a copy-paste mistake upstream or somehow intentional... PR coming up

**Comment by BellwetherLogic** [comment]
Adding to the pile, had this happen on Arena last night after everything worked fine in Lighthouse.

**Comment by deltanedas** [comment]
its fixed now

**Comment by BellwetherLogic** [comment]
Hey guess what I just got this bug on Edge post-patch

sorry :<

**Comment by BellwetherLogic** [comment]
I kept a tally of all the rounds I played yesterday post patch. 

- Hive ✅ 
- Hammurabi (didn't play AI, died to nukies before I could check)
- Hive ✅ 
- Edge ❌ 
- Tortuga ❌ 
- Hammurabi ❌ (doesn't have holopads, though the AI said they weren't working; might have meant an earlier round?) 
- Arena ❌ (ghostrolled, AI couldn't hear holopads) 
- Hive ❌ (ghostrolled, AI couldn't hear holopads)

I am consistently able to hear holopads more often on Hive (though it still has the announcement faraday cage issue), but it's not 100%, as illustrated above. It could just be weird randomness.

**Comment by chromiumboy** [comment]
Thanks for taking the time to check all of these maps! Do you happen to know if the affected maps have more than one AI core on them?

**Comment by IamVelcroboy** [comment]
> Thanks for taking the time to check all of these maps! Do you happen to know if the affected maps have more than one AI core on them?

Non of the maps should have more than 1 core but...I wonder if it has anything to do with the empty core we put in CC?

**Comment by chromiumboy** [comment]
> > Thanks for taking the time to check all of these maps! Do you happen to know if the affected maps have more than one AI core on them?
> 
> Non of the maps should have more than 1 core but...I wonder if it has anything to do with the empty core we put in CC?

That would do it. See here: https://github.com/space-wizards/space-station-14/pull/34248#issuecomment-2575570370

**Comment by IamVelcroboy** [comment]
> > Non of the maps should have more than 1 core but...I wonder if it has anything to do with the empty core we put in CC?
> 
> That would do it. See here: [space-wizards/space-station-14#34248 (comment)](https://github.com/space-wizards/space-station-14/pull/34248#issuecomment-2575570370)

I see. Is it recommended to remove from CC then? Or is there a fix planned?

**Comment by chromiumboy** [comment]
> > > Non of the maps should have more than 1 core but...I wonder if it has anything to do with the empty core we put in CC?
> > 
> > 
> > That would do it. See here: [space-wizards/space-station-14#34248 (comment)](https://github.com/space-wizards/space-station-14/pull/34248#issuecomment-2575570370)
> 
> I see. Is it recommended to remove from CC then? Or is there a fix planned?

It's a very simple fix, it needs to be made upstream though. I'm just unfortunately out of town ATM and can't do it myself, but someone else can do it and I'll approve it

**Comment by IamVelcroboy** [comment]
> It's a very simple fix, it needs to be made upstream though. I'm just unfortunately out of town ATM and can't do it myself, but someone else can do it and I'll approve it

Thanks!
