### ISSUE TITLE
There are cameras on pebble that are wrongly named.

### ISSUE THREAD

**Issue by Adrian16199** [DeltaV-Station/Delta-v#508]
## Description

As an example: RD quarters are cemares that are showin mantis's room. QM room points at the mail room.
**Reproduction**

>Use camera's on pebble
>Get gaslighted by camera's names.

Camera that need to be renamed:
>command:
QM room is pointing at mailroom
RD bedroom pointing at mantis's room
>general
Outside chaple isnt really... outside the chaple but outside janitor/mailroom
arrivals/evacuation camera is just called camera
>Epistemics:
 has 2 cameras and none of em are named
 >Security:
 Armoury doesnt have a named camera
 Same goes for security outpost
 >Service:
 Kitchen's freezer room has no name camera.

**Screenshots**

![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/dc806b51-cdab-4e6e-9bf6-3bd0442a292d)
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/93f5af57-496d-4d62-afe9-6f1456b552b5)
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/ddfe346e-e123-4869-a050-cfe6eb14e07f)

**Additional context**

Going to update this with every single camera that I have found to be wrongly named, maybe even missin.

**Comment by IamVelcroboy** [comment]
Wasn't this fixed in the last update?

**Comment by Adrian16199** [comment]
Funnily it was not, i just updated the issue to show what cameras exactly since i recalled that this is an issue.
It was definitely not fixed.
