### ISSUE TITLE
AAC colors gone

### ISSUE THREAD

**Issue by keekee38** [DeltaV-Station/Delta-v#5090]
## Description
the AAC tablet no longer has colors for its different sections

**Reproduction**
open the aac tablet

**Screenshots**
![Image](https://github.com/user-attachments/assets/5edcbd6d-9010-4e2d-b80a-97a48874b803)

**Additional context**
my guess is the upstream merge, specifically 41120, as that changed stylenano but i have no clue,

**Comment by ShepardToTheStars** [comment]
Probably due to the StyleNano removal.

**Comment by ShepardToTheStars** [comment]
Fixed in #5153

**Comment by keekee38** [comment]
heya so i hope im not coming across rude if i mention it but its still not fixed, i meant the colors of like
the department buttons et
they used to have colors that correlated with their departments

<img width="577" height="330" alt="Image" src="https://github.com/user-attachments/assets/2ccab267-f48d-485c-bc85-cb7f6214ac4e" />

like command used to be dark blue and engineering was yellow etc and they're all gray which just makes it a bit more
i guess difficult to use cause the whole subject tab has alot in it which makes for alotta scrolling and easy to get lost
i think i found how it used to work when aac's were first made but it was killed when the whole stylenano was removed and idunno anything code wise honestly and i tried but i got no clue how to get it working and its kinda terrifying to look at
sorry if that doesnt make sense

**Comment by keekee38** [comment]
<img width="526" height="433" alt="Image" src="https://github.com/user-attachments/assets/09b41d70-485c-4b46-b05a-12323522d167" />
heres a comparison if it helps
